[alembic]
script_location = %(here)s/alembic
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = src

[loggers]
keys = root

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = WARNING
handlers =
